appPackage = JSON.parse(File.read(File.join('..', 'node_modules', '@react-native-firebase', 'app', 'package.json')))
$FirebaseSDKVersion = appPackage['sdkVersions']['ios']['firebase']
$RNFirebaseAsStaticFramework=true
$RNFirebaseAnalyticsWithoutAdIdSupport=true

platform :ios, '13.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

  target 'audioBook' do
    config = use_native_modules!
    # Flags change depending on the env values.
    flags = get_default_flags()
    use_frameworks! :linkage => :static
    use_modular_headers!
    use_react_native!(
        :path => config[:reactNativePath],
        # Hermes is now enabled by default. Disable by setting this flag to false.
        # Upcoming versions of React Native may rely on get_default_flags(), but
        # we make it explicit here to aid in the React Native upgrade process.
        :hermes_enabled => true,
        :fabric_enabled => flags[:fabric_enabled],
        # Enables Flipper.
        #
        # Note that if you have use_frameworks! enabled, Flipper will not work and
        # you should disable the next line.
        # :flipper_configuration => FlipperConfiguration.enabled,
        # An absolute path to your application root.
        :app_path => "#{Pod::Config.instance.installation_root}/.."
      )
  # Pods for audioBook
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'Firebase/Analytics'
  pod 'Firebase/Performance'
  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'
  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'react-native-track-player', :path => '../node_modules/react-native-track-player'

  pod 'react-native-video', :path => '../node_modules/react-native-video'
  
  pod 'RNIap', :path => '../node_modules/react-native-iap'
  
  # add this here
  pod 'OneSignalXCFramework', '>= 3.0', '< 4.0'
  #end of add this here
  
  pod 'Branch'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'audioBookTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
end

target 'audioBook-tvOS' do
  # Pods for audioBook-tvOS

  target 'audioBook-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
