export const STORE_INPUT = 'STORE_INPUT';
export const STORE_MEDIA = 'STORE_MEDIA';
export const UPDATE_AUDIO_FILES = 'UPDATE_AUDIO_FILES';
export const STORE_REFERENCES = 'STORE_REFERENCES';
export const TOGGLE_REFS_VIEW = 'TOGGLE_REFS_VIEW';